apiVersion: networking.tytik.cloud/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: temp
    app.kubernetes.io/managed-by: kustomize
  name: ingress-sample
spec:
  # TODO(user): Add fields here
